# Generated by Django 5.1.4 on 2025-04-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CompareApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compareitem",
            name="product_id",
            field=models.CharField(max_length=255),
        ),
    ]
