# Generated by Django 5.1.4 on 2025-05-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0003_copy_table_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='casing',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='casing',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='casing',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hdd',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='hdd',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='hdd',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headphone',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='ram',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='ram',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='New arrival product'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Product on sale'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='name',
            field=models.CharField(blank=True, help_text='Product name', max_length=200, null=True),
        ),
    ]
