# Generated by Django 5.1.4 on 2025-04-06 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PCBuilder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the configuration",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Make this build visible to other users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="For non-logged in users",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pcbuilderapp_builds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCBuilderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("CPU", "CPU"),
                            ("Cooler", "CPU Cooler"),
                            ("Motherboard", "Motherboard"),
                            ("RAM", "Memory"),
                            ("SSD", "SSD"),
                            ("HDD", "HDD"),
                            ("GPU", "Graphics Card"),
                            ("Power Supply", "Power Supply"),
                            ("Casing", "Case"),
                            ("Monitor", "Monitor"),
                            ("Keyboard", "Keyboard"),
                            ("Mouse", "Mouse"),
                            ("Headphone", "Headphone"),
                        ],
                        max_length=50,
                    ),
                ),
                ("product_id", models.UUIDField(blank=True, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product_tdp",
                    models.IntegerField(
                        blank=True, help_text="Component TDP in watts", null=True
                    ),
                ),
                (
                    "pc_builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PCBuilderApp.pcbuilder",
                    ),
                ),
            ],
            options={
                "unique_together": {("pc_builder", "component_type")},
            },
        ),
    ]
